### ISSUE TITLE
请教一下 Uncaught error in rebar_core. Run with DIAGNOSTIC=1 to see stacktrace or consult rebar3.crashdump

### ISSUE THREAD

**Issue by colincodefirst** [caijinpeng1113/emqx_plugin_kafka#1]
===> Release successfully assembled: _build/default/rel/emqx_plugin_kafka
===> Uncaught error in rebar_core. Run with DIAGNOSTIC=1 to see stacktrace or consult rebar3.crashdump
===> When submitting a bug report, please include the output of `rebar3 report "your command"`
make: *** [Makefile:51: rel] Error 1

**Comment by caijinpeng1113** [comment]
看日志是rebar3报错， 没有具体的打印。 你能说一下这边环境配置吗？

参考： Erlang/OTP 25.2.2 + rebar3-3.20.0  ， 并且在rebar3安装时候，在rebar.config文件,  文件末尾添加 {plugins, [rebar3_hex]}.

**Comment by kelpliu** [comment]
同问，我编译时也遇到了同样的问题

**Comment by kelpliu** [comment]
>同问，我编译时也遇到了同样的问题，下面是编译时的消息
![image](https://github.com/caijinpeng1113/emqx_plugin_kafka/assets/17726590/fb2f9bbf-3f49-4c5c-b917-a1023f55f3c1)

**Comment by zhuchunlai** [comment]
> 看日志是rebar3报错， 没有具体的打印。 你能说一下这边环境配置吗？
> 
> 参考： Erlang/OTP 25.2.2 + rebar3-3.20.0 ， 并且在rebar3安装时候，在rebar.config文件, 文件末尾添加 {plugins, [rebar3_hex]}.

我采用的就是这个环境，并且也在rebar.config中追加了配置，依旧报这个错误，详细信息如下：

Error: badarg
[{erlang,iolist_to_binary,
         [[74,111,115,116,97,114,12289,67,97,105,106,105,110,112,101,110,103]],
         [{error_info,#{module => erl_erts_errors}}]},
 {emqx_plugrel,bin,1,
               [{file,"/opt/emqx_plugin_kafka/_build/default/plugins/emqx_plugrel/src/emqx_plugrel.erl"},
                {line,144}]},
 {lists,map,2,[{file,"lists.erl"},{line,1315}]},
 {emqx_plugrel,'-info_map/1-fun-0-',1,
               [{file,"/opt/emqx_plugin_kafka/_build/default/plugins/emqx_plugrel/src/emqx_plugrel.erl"},
                {line,155}]},
 {lists,map,2,[{file,"lists.erl"},{line,1315}]},
 {emqx_plugrel,info_map,1,
               [{file,"/opt/emqx_plugin_kafka/_build/default/plugins/emqx_plugrel/src/emqx_plugrel.erl"},
                {line,155}]},
 {emqx_plugrel,collect_info,5,
               [{file,"/opt/emqx_plugin_kafka/_build/default/plugins/emqx_plugrel/src/emqx_plugrel.erl"},
                {line,50}]},
 {emqx_plugrel,do,1,
               [{file,"/opt/emqx_plugin_kafka/_build/default/plugins/emqx_plugrel/src/emqx_plugrel.erl"},
                {line,36}]}]

**Comment by caijinpeng1113** [comment]
由于服务器操作系统变更啦，   在 RockyLinux 9.2环境下， 基于 Erlang/OTP 25.3.2.5 和  rebar3-3.20.0，重新编译一下，是很顺利。

如果是kafka转发插件的问题， 可以基于emqx 5.4源码编译，然后使用我编译后的kafka插件试试。
